-- Persistent metadata schema. Secrets and media blobs are intentionally excluded.
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS workspaces (id UUID PRIMARY KEY, name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS projects (id UUID PRIMARY KEY, workspace_id UUID REFERENCES workspaces(id), name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS conversations (id UUID PRIMARY KEY, project_id UUID REFERENCES projects(id), title TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS messages (id UUID PRIMARY KEY, conversation_id UUID REFERENCES conversations(id), role TEXT NOT NULL, content JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tasks (id UUID PRIMARY KEY, project_id UUID REFERENCES projects(id), kind TEXT NOT NULL, state TEXT NOT NULL, input JSONB NOT NULL DEFAULT '{}', output JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS task_steps (id UUID PRIMARY KEY, task_id UUID REFERENCES tasks(id), step_key TEXT NOT NULL, state TEXT NOT NULL, attempt INT NOT NULL DEFAULT 0, output JSONB, error TEXT, UNIQUE(task_id, step_key));
CREATE TABLE IF NOT EXISTS task_dependencies (task_id UUID REFERENCES tasks(id), depends_on UUID REFERENCES tasks(id), PRIMARY KEY(task_id, depends_on));
CREATE TABLE IF NOT EXISTS execution_runs (id UUID PRIMARY KEY, task_id UUID REFERENCES tasks(id), state TEXT NOT NULL, started_at TIMESTAMPTZ, finished_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS execution_events (id BIGSERIAL PRIMARY KEY, run_id UUID REFERENCES execution_runs(id), event_type TEXT NOT NULL, payload JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS providers (id UUID PRIMARY KEY, name TEXT UNIQUE NOT NULL, capability TEXT NOT NULL, pricing TEXT NOT NULL, endpoint_ref TEXT, status TEXT NOT NULL, priority INT NOT NULL DEFAULT 100, last_tested_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS provider_models (id UUID PRIMARY KEY, provider_id UUID REFERENCES providers(id), model TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS provider_capabilities (provider_id UUID REFERENCES providers(id), capability TEXT NOT NULL, PRIMARY KEY(provider_id, capability));
CREATE TABLE IF NOT EXISTS provider_health (provider_id UUID PRIMARY KEY REFERENCES providers(id), healthy BOOLEAN NOT NULL, latency_ms INT NOT NULL DEFAULT 0, score DOUBLE PRECISION, checked_at TIMESTAMPTZ NOT NULL DEFAULT now(), message TEXT);
CREATE TABLE IF NOT EXISTS provider_usage (id BIGSERIAL PRIMARY KEY, provider_id UUID REFERENCES providers(id), run_id UUID, tokens BIGINT, requests BIGINT, cost NUMERIC, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS provider_quotas (provider_id UUID PRIMARY KEY REFERENCES providers(id), remaining BIGINT, reset_at TIMESTAMPTZ, metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS fallback_routes (id UUID PRIMARY KEY, capability TEXT NOT NULL, provider_id UUID REFERENCES providers(id), rank INT NOT NULL);
CREATE TABLE IF NOT EXISTS mcp_servers (id UUID PRIMARY KEY, name TEXT UNIQUE NOT NULL, url TEXT, command TEXT, enabled BOOLEAN NOT NULL DEFAULT TRUE, permissions JSONB NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS mcp_tools (id UUID PRIMARY KEY, server_id UUID REFERENCES mcp_servers(id), name TEXT NOT NULL, description TEXT, input_schema JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS mcp_resources (id UUID PRIMARY KEY, server_id UUID REFERENCES mcp_servers(id), uri TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS skills (id UUID PRIMARY KEY, name TEXT UNIQUE NOT NULL, active_version TEXT, metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS skill_versions (id UUID PRIMARY KEY, skill_id UUID REFERENCES skills(id), version TEXT NOT NULL, instructions TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}', UNIQUE(skill_id, version));
CREATE TABLE IF NOT EXISTS skill_runs (id UUID PRIMARY KEY, skill_id UUID REFERENCES skills(id), version TEXT, task_id UUID, state TEXT NOT NULL, error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS artifacts (id UUID PRIMARY KEY, project_id UUID REFERENCES projects(id), task_id UUID, type TEXT NOT NULL, drive_file_id TEXT, drive_folder_id TEXT, filename TEXT NOT NULL, mime_type TEXT, size BIGINT, checksum TEXT, version INT NOT NULL DEFAULT 1, status TEXT NOT NULL, parent_artifact_id UUID REFERENCES artifacts(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS files (id UUID PRIMARY KEY, project_id UUID REFERENCES projects(id), artifact_id UUID REFERENCES artifacts(id), filename TEXT NOT NULL, mime_type TEXT, size BIGINT, checksum TEXT, drive_file_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS research_projects (id UUID PRIMARY KEY, project_id UUID REFERENCES projects(id), question TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS research_sources (id UUID PRIMARY KEY, research_project_id UUID REFERENCES research_projects(id), url TEXT NOT NULL, title TEXT, excerpt TEXT, quality DOUBLE PRECISION, fetched_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS video_projects (id UUID PRIMARY KEY, project_id UUID REFERENCES projects(id), status TEXT NOT NULL, output_artifact_id UUID REFERENCES artifacts(id));
CREATE TABLE IF NOT EXISTS video_scenes (id UUID PRIMARY KEY, video_project_id UUID REFERENCES video_projects(id), scene_index INT NOT NULL, description TEXT, metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS video_shots (id UUID PRIMARY KEY, scene_id UUID REFERENCES video_scenes(id), shot_index INT NOT NULL, prompt TEXT, duration_ms INT, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS video_clips (id UUID PRIMARY KEY, shot_id UUID REFERENCES video_shots(id), artifact_id UUID REFERENCES artifacts(id), quality_score DOUBLE PRECISION, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS video_timelines (id UUID PRIMARY KEY, video_project_id UUID REFERENCES video_projects(id), manifest JSONB NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS render_jobs (id UUID PRIMARY KEY, video_project_id UUID REFERENCES video_projects(id), status TEXT NOT NULL, progress DOUBLE PRECISION NOT NULL DEFAULT 0, error TEXT);
CREATE TABLE IF NOT EXISTS memory (id UUID PRIMARY KEY, workspace_id UUID REFERENCES workspaces(id), kind TEXT NOT NULL, content JSONB NOT NULL, sensitivity TEXT NOT NULL DEFAULT 'private', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_state (workspace_id UUID PRIMARY KEY REFERENCES workspaces(id), state JSONB NOT NULL DEFAULT '{}', updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS logs (id BIGSERIAL PRIMARY KEY, run_id UUID, level TEXT NOT NULL, message TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS errors (id BIGSERIAL PRIMARY KEY, run_id UUID, error_class TEXT NOT NULL, message TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_events (id BIGSERIAL PRIMARY KEY, workspace_id UUID, actor TEXT, action TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS permissions (workspace_id UUID REFERENCES workspaces(id), permission TEXT NOT NULL, allowed BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY(workspace_id, permission));
